import { configureConfig, type ConfigMap } from '@library/domain';
import {
  APPMETRICA_API_KEY,
  AUTH_ACTIVE_TIMEOUT,
  DEPLOY_ENV,
  GATEWAY_HOST_API,
  GATEWAY_HOST_API_DEMO,
  GATEWAY_WALLETS_BFF_API,
  GATEWAY_WALLETS_BFF_API_DEMO,
  SECURE_STORAGE_SECRET_KEY,
  SENTRY_API,
  SENTRY_TRACE_PROPAGATION_TARGETS,
} from '@config/env';

configureConfig({
  APPMETRICA_API_KEY,
  AUTH_ACTIVE_TIMEOUT,
  DEPLOY_ENV,
  GATEWAY_HOST_API,
  GATEWAY_HOST_API_DEMO,
  GATEWAY_WALLETS_BFF_API,
  GATEWAY_WALLETS_BFF_API_DEMO,
  SECURE_STORAGE_SECRET_KEY,
  SENTRY_API,
  SENTRY_TRACE_PROPAGATION_TARGETS,
} satisfies ConfigMap);
